#!/bin/bash

BRANCH_NAME=$(git symbolic-ref HEAD 2> /dev/null | cut -b 12-)
if [[ -n "$BRANCH_NAME" ]] && [[ "$BRANCH_NAME" =~ ^feature\/ ]] ; then
  BRANCH_NAME=${BRANCH_NAME/feature\/}
  BRANCH_NAME=${BRANCH_NAME//[-_]/ }
  printf "${BRANCH_NAME[@]^}:\n$(cat $1)" > $1
fi